# Anomalías en Datos JSON vs. Noticias Hondureñas

Correlación entre anomalías detectadas en los snapshots JSON del CNE y reportes de medios sobre caídas, fallas técnicas o retrasos.

| Fecha aproximada | Anomalía principal en JSON | Noticia relacionada (resumen) | Enlace a la noticia | Captura de respaldo |
|------------------|----------------------------|-------------------------------|---------------------|---------------------|
| 8 dic 2025 ~14:00-17:00 | Pausa de 3 horas en snapshots + salto masivo de votos después (reversión de tendencia) | CNE atribuye caída del sistema a problemas técnicos | https://www.infobae.com/america/america-latina/2025/12/07/el-cne-de-honduras-atribuyo-la-caida-del-sistema-de-escrutinio-a-problemas-tecnicos-el-proceso-ha-sido-una-batalla-constante/ | [Ver captura](evidence/news-screenshots/screencapture-infobae-america-america-latina-2025-12-07-el-cne-de-honduras-atribuyo-la-caida-del-sistema-de-escrutinio-a-problemas-tecnicos-el-proceso-ha-sido-una-batalla-constante-2025-12-27-17_48_15.png) |
| 8 dic 2025 ~17:00 | Salto desproporcionado de votos a favor de Asfura tras la pausa | Reanudación del conteo después de fallas técnicas | https://cnnespanol.cnn.com/2025/12/08/latinoamerica/cne-honduras-reanuda-conteo-votos-orix | [Ver captura](evidence/news-screenshots/screencapture-cnnespanol-cnn-2025-12-08-latinoamerica-cne-honduras-reanuda-conteo-votos-orix-2025-12-27-18_21_27.png) |
| 8-9 dic 2025 | Adición injustificada de +15 actas totales | Suspensión del conteo por fallas y empate técnico | https://www.energiaestrategica.com/honduras-sin-presidente-electo-tras-48-horas-el-cne-suspende-el-conteo-en-medio-de-empate-tecnico/ | [Ver captura](evidence/news-screenshots/screencapture-energiaestrategica-honduras-sin-presidente-electo-tras-48-horas-el-cne-suspende-el-conteo-en-medio-de-empate-tecnico-2025-12-27-18_22_01.png) |
| Desde 9 dic 2025 | Estancamiento en 99.4% con 2,773 actas inconsistentes | Retrasos injustificados y tensiones por denuncias de fraude | https://www.infobae.com/america/america-latina/2025/12/10/el-cne-de-honduras-dijo-que-los-problemas-tecnicos-en-el-sistema-no-comprometieron-los-resultados-de-las-elecciones/ | [Ver captura](evidence/news-screenshots/screencapture-infobae-america-america-latina-2025-12-10-el-cne-de-honduras-dijo-que-los-problemas-tecnicos-en-el-sistema-no-comprometieron-los-resultados-de-las-elecciones-2025-12-27-18_22_35.png) |
